# -*- coding: utf-8 -*-
"""6Naïve_Bayes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_Jaoxu8F2-X66cLcgc3ZIQCXLifnN3lL

# Naive Bayes

## Importing the libraries
"""

import numpy as np
import pandas as pd

"""## Importing the dataset"""

dataset = pd.read_csv('data6.csv')
dataset

X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

"""## Splitting the dataset into the Training set and Test set"""

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 2)

"""## Training the Naive Bayes model on the Training set"""

from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

"""## Predicting the Test set results"""

y_pred = classifier.predict(X_test)
y_pred

# Evaluate the performance of Model for train_y and
from sklearn.metrics import precision_score,confusion_matrix,accuracy_score,recall_score
accuracy = accuracy_score(y_test,y_pred)
precision =precision_score(y_test, y_pred,average='micro')
recall = recall_score(y_test, y_pred,average='micro')
print(f"Accuracy: {accuracy}")
print(f"Precision: {precision}")
print(f"Recall: {recall}")

"""## Making the Confusion Matrix"""

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
# Display the confusion matrix and evaluation metrics
print("Confusion Matrix:")
print(cm)

# Predicting the result
from sklearn.preprocessing import StandardScaler
# Feature Scaling (assuming you want to scale your features)
sc = StandardScaler()
X_train = sc.fit_transform(X_train)  # Fit and transform the training set
X_test = sc.transform(X_test)  # Only transform the test set

# Accept user input for prediction
age = float(input("Enter age: "))
salary = float(input("Enter salary: "))

# Scale the input before making the prediction
scaled_input = sc.transform([[age, salary]])  # Scale the input values
prediction = classifier.predict(scaled_input)  # Make the prediction

print(f"The predicted class for age {age} and salary {salary} is: {prediction[0]}")