# -*- coding: utf-8 -*-
"""6Naïve_Bayes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_Jaoxu8F2-X66cLcgc3ZIQCXLifnN3lL

# Naive Bayes
What is Naive Bayes?

Naive Bayes is a Machine Learning Classification Algorithm used to predict categories/classes.

It works using Bayes Theorem and probability.

Example Uses
Spam email detection
Disease prediction
Sentiment analysis
Student result prediction
Customer buying prediction
Main Idea of Naive Bayes

It predicts using probabilities.

Example:

If:

Young people usually buy products
High salary people also buy products

Then model predicts whether a new person may buy or not.

The word “Naive” means:

It assumes all features are independent from each other.
Bayes Theorem

Central formula behind Naive Bayes:

P(A∣B)=
P(B)
P(B∣A)P(A)
	​

P(A)
P(B∣A)
P(B∣¬A)
P(A∣B)=
P(B)
P(B∣A)P(A)
	​

≈0.68,P(B)≈0.25
P(B)=0.25
P(B|A)P(A)=0.17
P(A|B)~0.68
Posterior = useful evidence / total evidence
Meaning
P(A|B) → Probability of A when B happens
Used for prediction using known data

You don't need to calculate manually because sklearn does it automatically.

## Importing the libraries
"""

import numpy as np
import pandas as pd

"""## Importing the dataset
X

Stores independent variables/features.

Example:

[[25,50000],
 [40,90000]]
y

Stores target/output column.

Example:

[0,1]"""

dataset = pd.read_csv('data6.csv')
dataset

X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values


"""## Splitting the dataset into the Training set and Test set"""

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 2)

"""## Training the Naive Bayes model on the Training set
Explanation

Dataset divided into:

Training data
Testing data
Why?

Model learns from training data and checks accuracy on testing data.

test_size = 0.25
25% data for testing
75% data for training
random_state = 2

Used to get same random split every time."""

from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

"""## Predicting the Test set results
Explanation
GaussianNB

Naive Bayes model for continuous numeric values.

fit()

Trains model using training data.

Why Gaussian?

Because data like:

Age
Salary

are continuous numeric values.

Gaussian means it assumes data follows normal distribution (bell curve).

Logic Behind Training

Model learns:

Which age/salary belongs to which class
Probability patterns

Example:

High salary → more chance to purchase
Young age → less chance
"""

y_pred = classifier.predict(X_test)
y_pred
"""xplanation

Model predicts outputs for testing data.

Example:

[1 0 1 1]

Meaning:

1 = Purchased
0 = Not Purchased"""

# Evaluate the performance of Model for train_y and
from sklearn.metrics import precision_score,confusion_matrix,accuracy_score,recall_score
#These functions evaluate model performance.
accuracy = accuracy_score(y_test,y_pred)
"""Formula

Accuracy=
Total Predictions
Correct Predictions
	​


Meaning

How many predictions are correct.

Example:

90 correct out of 100
Accuracy = 90%"""

precision =precision_score(y_test, y_pred,average='micro')

"""Meaning

Out of predicted YES values, how many are actually YES.

Used when false positives matter.

Example:
Spam detection."""

recall = recall_score(y_test, y_pred,average='micro')

"""Meaning

Out of actual YES values, how many were correctly predicted.

Used in disease detection."""

print(f"Accuracy: {accuracy}")
print(f"Precision: {precision}")
print(f"Recall: {recall}")

#Print Results

"""## Making the Confusion Matrix"""

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
# Display the confusion matrix and evaluation metrics
print("Confusion Matrix:")
print(cm)

"""What is Confusion Matrix?

Table showing:

Correct predictions
Wrong predictions

Example:

Actual/Predicted	0	1
0	40	5
1	3	52
Terms
True Positive (TP)

Correct YES prediction

True Negative (TN)

Correct NO prediction

False Positive (FP)

Wrong YES prediction

False Negative (FN)

Wrong NO prediction"""

# Predicting the result
from sklearn.preprocessing import StandardScaler
# Feature Scaling (assuming you want to scale your features)

"""Why Scaling?

Age and Salary have different ranges.

Example:

Age = 25
Salary = 50000

Large salary values dominate calculations.

Scaling converts data into similar range.

Scaling Formula
z=
σ
x−μ
	​

x
μ
σ
z=
σ
x−μ
	​

≈1.2
Φ(z)≈88.5%

Where x = original value
μ = mean
σ = standard deviation"""
sc = StandardScaler()
X_train = sc.fit_transform(X_train)  # Fit and transform the training set
X_test = sc.transform(X_test)  # Only transform the test set
"""fit_transform()
Learns scaling from training data
Applies scaling
transform()

Only applies learned scaling on test data."""
# Accept user input for prediction
age = float(input("Enter age: "))
salary = float(input("Enter salary: "))

# Scale the input before making the prediction
scaled_input = sc.transform([[age, salary]])  # Scale the input values
prediction = classifier.predict(scaled_input)  # Make the prediction

print(f"The predicted class for age {age} and salary {salary} is: {prediction[0]}")

"""Import Libraries
       ↓
Load Dataset
       ↓
Split Input & Output
       ↓
Split Train/Test Data
       ↓
Train Naive Bayes Model
       ↓
Predict Test Data
       ↓
Check Accuracy
       ↓
Scale Features
       ↓
Take User Input
       ↓
Predict New Result

Advantages of Naive Bayes
Simple and fast
Works well with small datasets
Good for classification problems
Easy to implement
Less training time
Disadvantages
Assumes features are independent
Accuracy may reduce for complex data
Not best for highly correlated data
Important Viva/Oral Questions
1. What is Naive Bayes?

A probability-based classification algorithm using Bayes theorem.

2. Why called “Naive”?

Because it assumes all features are independent.

3. What is GaussianNB?

Naive Bayes model for continuous numeric data.

4. Why use train_test_split?

To divide data into training and testing sets.

5. Why feature scaling is used?

To bring all features into same range.

6. Difference between fit() and predict()
fit()

Used for training.

predict()

Used for prediction.

Real Life Example

Suppose:

Age	Salary	Buy Phone
22	20000	No
35	70000	Yes

If new customer:

Age = 30
Salary = 65000

Naive Bayes predicts:

Yes

because probability is higher for purchase.s"""



""" 

Naive Bayes Program
What is this Code About?

This program implements the Naive Bayes Classification Algorithm using Python and Machine Learning libraries.

The program:

Loads a dataset
Trains a Naive Bayes model
Predicts outputs
Checks model accuracy
Takes user input (Age & Salary)
Predicts whether a customer will purchase or not

This is a Supervised Machine Learning Classification Problem.

Purpose of This Code

The main purpose of this program is:

To classify data into categories
To predict outcomes using probability
To learn patterns from existing data
To make predictions for new data
Example

Using:

Age
Salary

the model predicts:

Purchased = 1
Not Purchased = 0
Theory Concepts Used
1. Machine Learning Classification

Classification means predicting categories/classes.

Examples
Spam / Not Spam
Disease / No Disease
Purchased / Not Purchased

Naive Bayes is a classification algorithm.

2. Naive Bayes Algorithm

Naive Bayes is a probability-based Machine Learning algorithm.

It uses:

Bayes Theorem
Probability concepts

The word Naive means:

It assumes all input features are independent from each other.

3. Bayes Theorem

Main formula behind Naive Bayes:

P(A∣B)=
P(B)
P(B∣A)P(A)
	​

P(A)
P(B∣A)
P(B∣¬A)
P(A∣B)=
P(B)
P(B∣A)P(A)
	​

≈0.68,P(B)≈0.25
P(B)=0.25
P(B|A)P(A)=0.17
P(A|B)~0.68
Posterior = useful evidence / total evidence
Meaning
Term	Meaning
P(A|B)	Probability of A when B happens
P(B|A)	Probability of B when A happens
P(A)	Probability of A
P(B)	Probability of B
4. Gaussian Naive Bayes

The program uses:

GaussianNB()

GaussianNB is used for:

Continuous numeric data
Normally distributed data
Example
Age
Salary

These are continuous values.

Gaussian assumes data follows a bell curve distribution.

5. Train-Test Split

Dataset is divided into:

Training Data → Model learns
Testing Data → Model checks performance
Used in code
train_test_split()
Why?

To evaluate whether model predictions are correct.

6. Feature Scaling

Feature scaling is done using:

StandardScaler()
Why Scaling is Needed?

Different features have different ranges.

Example:

Age = 25
Salary = 50000

Large salary values can dominate calculations.

Scaling converts values into similar range.

Scaling Formula
z=
σ
x−μ
	​

x
μ
σ
z=
σ
x−μ
	​

≈1.2
Φ(z)≈88.5%
Where
Symbol	Meaning
x	Original value
μ	Mean
σ	Standard deviation
z	Scaled value
7. Model Evaluation Metrics

The program checks model performance using:

Accuracy

Measures total correct predictions.

Formula:

Accuracy=
Total Predictions
Correct Predictions
	​


Example

90 correct predictions out of 100

Accuracy = 90%

Precision

Measures:

Out of predicted YES values, how many are actually YES.

Used when False Positives matter.

Example

Spam Email Detection

Recall

Measures:

Out of actual YES values, how many are correctly predicted.

Used in:

Disease prediction
Fraud detection
8. Confusion Matrix

Confusion Matrix shows:

Correct predictions
Wrong predictions
Example Table
Actual / Predicted	0	1
0	40	5
1	3	52
Terms in Confusion Matrix
Term	Meaning
TP	True Positive
TN	True Negative
FP	False Positive
FN	False Negative
Real Life Example
Age	Salary	Buy Phone
22	20000	No
35	70000	Yes

For new customer:

Age = 30
Salary = 65000

Naive Bayes predicts:

YES

because probability of purchase is higher.

Why We Do This Program?

This program helps to:

Understand Machine Learning classification
Learn probability-based prediction
Predict future outcomes
Evaluate model performance
Use real-world ML workflow
Applications of Naive Bayes
Spam email detection
Disease prediction
Sentiment analysis
Customer purchase prediction
Student result prediction
Advantages of Naive Bayes
Simple and easy
Fast algorithm
Works well on small datasets
Less training time
Good for classification problems
Easy implementation
Disadvantages of Naive Bayes
Assumes features are independent
Accuracy may reduce for complex datasets
Not suitable for highly correlated data
Sometimes oversimplifies prediction
Important Concepts Used in Program
Concept	Purpose
Pandas	Dataset handling
NumPy	Numerical operations
train_test_split	Split dataset
GaussianNB	Train Naive Bayes model
predict()	Predict outputs
accuracy_score	Calculate accuracy
confusion_matrix	Show prediction results
StandardScaler	Feature scaling
Overall Working of Program
Import libraries
Load dataset
Separate input and output variables
Split dataset into training and testing
Train Naive Bayes model
Predict test data
Calculate accuracy, precision, recall
Create confusion matrix
Scale features
Take user input
Predict final result
Algorithm / Steps of Program
Algorithm
Step 1

Import required libraries.

Step 2

Load dataset using pandas.

Step 3

Separate independent variables (X) and dependent variable (y).

Step 4

Split dataset into training and testing sets.

Step 5

Train the Naive Bayes model using GaussianNB.

Step 6

Predict outputs for testing data.

Step 7

Evaluate model using:

Accuracy
Precision
Recall
Step 8

Generate confusion matrix.

Step 9

Apply feature scaling using StandardScaler.

Step 10

Accept user input:

Age
Salary
Step 11

Scale input values.

Step 12

Predict final class/output.

Step 13

Display prediction result.

Final Conclusion

This program demonstrates how the Naive Bayes Machine Learning algorithm is used for classification problems.

The model learns patterns from training data and predicts outcomes for new data using probability and Bayes Theorem.
"""