# -*- coding: utf-8 -*-
"""Assignment_N0_9_Data_Visualization_II.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RAUTulN9GU6AnJkUJ0CIpjTq1qw8DapQ
"""

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

dataset=pd.read_csv('/content/train.csv')

dataset.head()

sns.boxplot(x='Sex', y='Age', data=dataset)

"""The box plot is used to display the distribution of the categorical data in the form of quartiles. The center of the box shows the median value. The value from the lower whisker to the bottom of the box shows the first quartile. From the bottom of the box to the middle of the box lies the second quartile. From the middle of the box to the top of the box lies the third quartile and finally from the top of the box to the top whisker lies the last quartile.
Now let's plot a box plot that displays the distribution for the age with respect to each gender. You need to pass the categorical column as the first parameter (which is sex in our case) and the numeric column (age in our case) as the second parameter. Finally, the dataset is passed as the third parameter

Let's try to understand the box plot for female. The first quartile starts at around 5 and ends at 22 which means that 25% of the passengers are aged between 5 and 25. The second quartile starts at around 23 and ends at around 32 which means that 25% of the passengers are aged between 23 and 32. Similarly, the third quartile starts and ends between 34 and 42, hence 25% passengers are aged within this range and finally the fourth or last quartile starts at 43 and ends around 65.

If there are any outliers or the passengers that do not belong to any of the quartiles, they are called outliers and are represented by dots on the box plot.

You can make your box plots more fancy by adding another layer of distribution. For instance, if you want to see the box plots of forage of passengers of both genders, along with the information about whether or not they survived, you can pass the survived as value to the hue parameter as shown below:
"""

sns.boxplot(x='Sex', y='Age', data=dataset, hue="Survived")

"""Now in addition to the information about the age of each gender, you can also see the distribution of the passengers who survived. For instance, you can see that among the male passengers, on average more younger people survived as compared to the older ones. Similarly, you can see that the variation among the age of female passengers who did not survive is much greater than the age of the surviving female passengers.

Boxplot is a very interesting plot that basically plots a 5 number summary. to get 5 number summary some terms we need to describe.
Median – Middle value in series after sorting
Percentile – Gives any number which is number of values present before this percentile like for example 50 under 25th percentile so it explains total of 50 values are there below 25th percentile
Minimum and Maximum – These are not minimum and maximum values, rather they describe the lower and upper boundary of standard deviation which is calculated using Interquartile range(IQR).
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from seaborn import load_dataset
#titanic dataset
data = pd.read_csv('/content/train.csv')
#tips dataset
tips = load_dataset("tips")

sns.boxplot(x='Survived', y='Fare', data=dataset)

sns.boxplot(x='Sex', y='Age', data=dataset)

sns.boxplot(x='Sex', y='Age', data=dataset)

sns.boxplot(x='Survived', y='Fare', data=dataset)


"""
Assignment No. 9 – Data Visualization II (Box Plot using Titanic Dataset)
What is this code about?

This program is about Data Visualization using Box Plot in Python with the Titanic dataset.
It uses the libraries Pandas, NumPy, Matplotlib, and Seaborn to analyze and visualize passenger data.

The program mainly shows:

Distribution of passenger Age
Comparison between Male and Female
Relationship between Survival and Fare
Detection of outliers
Understanding of quartiles and median

The Titanic dataset contains information like:

Age
Gender (Sex)
Fare
Survival status

The code helps in understanding the spread and variation of data visually.

Theory Concepts
1. Data Visualization

Data Visualization means representing data in graphical form so that it becomes easier to understand patterns, trends, and relationships.

Examples:

Bar Chart
Histogram
Pie Chart
Box Plot
2. Box Plot

A Box Plot (Box-and-Whisker Plot) is used to represent the statistical distribution of numerical data using a five-number summary.

It shows:

Minimum value
First Quartile (Q1)
Median (Q2)
Third Quartile (Q3)
Maximum value

It also helps to identify outliers.

3. Five Number Summary
a) Minimum

Smallest value in dataset.

b) First Quartile (Q1)

25% of data lies below this value.

c) Median (Q2)

Middle value after sorting the data.

d) Third Quartile (Q3)

75% of data lies below this value.

e) Maximum

Largest value in dataset.

4. Interquartile Range (IQR)

IQR measures the spread of middle 50% data.

Formula

IQR=Q3−Q1

Where:

Q1 = First Quartile
Q3 = Third Quartile
5. Outliers

Outliers are unusual values that are very high or very low compared to other data points.

In box plot:

Outliers are represented using dots.
Purpose of this Program

The purpose of this code is to:

Visualize Titanic passenger data
Compare age distribution between males and females
Analyze fare distribution
Study survival patterns
Detect outliers in data
Understand quartiles and median visually
Why do we use this code?

We use this program because:

Graphs are easier to understand than raw tables
Helps in statistical analysis
Finds variation in data
Detects abnormal values
Helps in machine learning preprocessing
Useful in exploratory data analysis (EDA)
Libraries Used
1. Pandas

Used for:

Reading dataset
Handling tables/dataframes
2. NumPy

Used for:

Numerical calculations
3. Matplotlib

Used for:

Creating graphs and plots
4. Seaborn

Used for:

Advanced statistical visualizations
Attractive box plots
Dataset Used

Dataset: Titanic Dataset (train.csv)

Contains:

Passenger age
Gender
Survival status
Fare amount
Types of Box Plots Used
1. Age vs Sex
sns.boxplot(x='Sex', y='Age', data=dataset)
Meaning

Shows age distribution of male and female passengers.

2. Age vs Sex with Survival
sns.boxplot(x='Sex', y='Age', data=dataset, hue='Survived')
Meaning

Shows:

Gender-wise age distribution
Survival comparison together
3. Fare vs Survival
sns.boxplot(x='Survived', y='Fare', data=dataset)
Meaning

Shows how fare varies between survived and non-survived passengers.

Example Interpretation

Example:
If median age for males is 30:

Half male passengers are below 30
Half are above 30

If dots appear above whiskers:

They are outliers
Advantages of Box Plot
Easy to understand distribution
Detects outliers clearly
Shows median and quartiles
Good for comparing categories
Useful in statistical analysis
Disadvantages of Box Plot
Does not show exact data values
Cannot display detailed distribution shape
Difficult for beginners sometimes
Small datasets may not give clear visualization
Real Life Uses

Box plots are used in:

Data Science
Machine Learning
Business Analytics
Medical Research
Finance Analysis
Survey Analysis

Example:

Comparing salaries of employees
Comparing marks of students
Analyzing hospital patient age groups
Overall Conclusion

This program performs statistical visualization using box plots on the Titanic dataset.
It helps to understand:

Data distribution
Quartiles
Median
Survival patterns
Outliers

It is an important part of Exploratory Data Analysis (EDA) in Data Science and Machine Learning.

Algorithm / Steps to Perform Program
Step 1

Import required libraries:

Pandas
NumPy
Matplotlib
Seaborn
Step 2

Load Titanic dataset using read_csv().

Step 3

Display first few records using head().

Step 4

Create box plot for:

Sex vs Age
Step 5

Create box plot using hue parameter:

Sex vs Age vs Survival
Step 6

Create box plot for:

Survival vs Fare
Step 7

Analyze:

Median
Quartiles
Outliers
Distribution
Step 8

Interpret the visualization results and conclusions.
"""