# -*- coding: utf-8 -*-
"""Assignment_N0_9_Data_Visualization_II.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RAUTulN9GU6AnJkUJ0CIpjTq1qw8DapQ
"""

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

dataset=pd.read_csv('/content/train.csv')

dataset.head()

sns.boxplot(x='Sex', y='Age', data=dataset)

"""The box plot is used to display the distribution of the categorical data in the form of quartiles. The center of the box shows the median value. The value from the lower whisker to the bottom of the box shows the first quartile. From the bottom of the box to the middle of the box lies the second quartile. From the middle of the box to the top of the box lies the third quartile and finally from the top of the box to the top whisker lies the last quartile.
Now let's plot a box plot that displays the distribution for the age with respect to each gender. You need to pass the categorical column as the first parameter (which is sex in our case) and the numeric column (age in our case) as the second parameter. Finally, the dataset is passed as the third parameter

Let's try to understand the box plot for female. The first quartile starts at around 5 and ends at 22 which means that 25% of the passengers are aged between 5 and 25. The second quartile starts at around 23 and ends at around 32 which means that 25% of the passengers are aged between 23 and 32. Similarly, the third quartile starts and ends between 34 and 42, hence 25% passengers are aged within this range and finally the fourth or last quartile starts at 43 and ends around 65.

If there are any outliers or the passengers that do not belong to any of the quartiles, they are called outliers and are represented by dots on the box plot.

You can make your box plots more fancy by adding another layer of distribution. For instance, if you want to see the box plots of forage of passengers of both genders, along with the information about whether or not they survived, you can pass the survived as value to the hue parameter as shown below:
"""

sns.boxplot(x='Sex', y='Age', data=dataset, hue="Survived")

"""Now in addition to the information about the age of each gender, you can also see the distribution of the passengers who survived. For instance, you can see that among the male passengers, on average more younger people survived as compared to the older ones. Similarly, you can see that the variation among the age of female passengers who did not survive is much greater than the age of the surviving female passengers.

Boxplot is a very interesting plot that basically plots a 5 number summary. to get 5 number summary some terms we need to describe.
Median – Middle value in series after sorting
Percentile – Gives any number which is number of values present before this percentile like for example 50 under 25th percentile so it explains total of 50 values are there below 25th percentile
Minimum and Maximum – These are not minimum and maximum values, rather they describe the lower and upper boundary of standard deviation which is calculated using Interquartile range(IQR).
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from seaborn import load_dataset
#titanic dataset
data = pd.read_csv('/content/train.csv')
#tips dataset
tips = load_dataset("tips")

sns.boxplot(x='Survived', y='Fare', data=dataset)

sns.boxplot(x='Sex', y='Age', data=dataset)

sns.boxplot(x='Sex', y='Age', data=dataset)

sns.boxplot(x='Survived', y='Fare', data=dataset)