# -*- coding: utf-8 -*-
"""Assignment4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-ETIAP1-Au-qCs9WemOJXx4Smn4qqO1j
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

"""Explanation
1. pandas (pd)

Used for:

handling tables/data
creating DataFrames

Example:
Like Excel sheet handling in Python.

2. numpy (np)

Used for:

arrays
mathematical operations

Example:
Store marks or numbers efficiently.

3. matplotlib.pyplot (plt)

Used for:

graphs
charts
visualization

Example:
Show regression line and points."""

x=np.array([95,85,80,70,60])
y=np.array([85,95,70,65,70])

"""Explanation

Here:

x = marks of students in 10th
y = marks of students in 12th

This is supervised learning data.

x → Independent variable
y → Dependent variable

We want to predict:

If 10th marks are known, what will be 12th marks?"""

model=np.polyfit(x,y,1)

"""Create Linear Regression Model
Explanation

np.polyfit() creates the best fit line.

Syntax
np.polyfit(x,y,degree)
Parameters
x → input values
y → output values
1 → degree 1 means straight line

Theory Behind It

This function uses:

Least Square Method

It tries to minimize prediction error.

Formula:

Y=mX+b
Where:

m = slope
b = intercept

Output of model
array([0.64383562, 26.78082192])

Meaning:

slope = 0.6438
intercept = 26.78

Equation becomes:

Y=0.6438X+26.78"""

predict=np.poly1d(model)

"""Explanation

Creates a prediction equation from model.

Now Python can calculate Y for any X."""
predict(65)

"""Explanation

Predicts 12th marks when 10th marks = 65.

Internally

Y=0.6438(65)+26.78

Result ≈ 68.6

Real Life Logic

Student got:

65 marks in 10th

Model predicts:

around 68 marks in 12th"""

y_pred=predict(x)
y_pred

"""Explanation

Predicts Y values for all X values.

Example
Actual Y	Predicted Y
85	81.5
95	87.9
Use

Used for:

checking model performance
comparing actual vs predicted"""
from sklearn.metrics import r2_score
r2_score(y,y_pred)

"""Explanation

Measures accuracy of regression model.

Theory
R² Score

Formula:
R
2
=
SST
SSR
	​


Range:

0 → bad model
1 → perfect model
Your Output
0.48

Meaning:

model explains 48% variation
average model"""

y_line = model[1] + model[0]* x

"""Creates equation line points.

Logic
y = mx + b

Where:

model[0] = slope
model[1] = intercept"""
plt.plot(x, y_line, c = 'r')
plt.scatter(x, y_pred)
plt.scatter(x,y,c='r')

"""Explanation
1. plt.plot()

Draws regression line.

2. plt.scatter(x,y_pred)

Shows predicted points.

3. plt.scatter(x,y,c='r')

Shows actual points.

Graph Logic

Graph helps visualize:

actual data
predicted data
best fit line"""



import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.datasets import fetch_california_housing
housing=fetch_california_housing()
data=pd.DataFrame(housing.data)
"""Explanation

Loads California house dataset.

Dataset contains:

house information
house prices
Converts dataset into table form."""

data.columns=housing.feature_names
data.head()
"""Adds meaningful column names.

Examples:

MedInc → median income
HouseAge → house age

data.head() shows first 5 rows."""

data['PRICE']=housing.target

"""Explanation

Adds house prices column.

Target variable:

PRICE"""

data.isnull().sum()

"""Explanation

Checks empty values in dataset.

Why Important?

Missing values can affect prediction accuracy."""

x=data.drop(['PRICE'],axis=1)
y=data['PRICE']

"""x

Contains input features.

y

Contains target/output.

Example

Inputs:

income
rooms
age

Output:

house price"""
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,random_state=0)


"""Splits data into:

training data
testing data
Meaning
80% Data

Used for training.

20% Data

Used for testing.

Theory
Why Split Data?

If we test on same training data:

model may memorize data
wrong accuracy comes

Testing on new data checks real performance."""

import sklearn
from sklearn.linear_model import LinearRegression
lm=LinearRegression()
#Creates Linear Regression object.

model=lm.fit(xtrain,ytrain)
"""Model learns patterns from training data.

Theory

Training means:

machine studies data
finds relationships
creates prediction equation"""

ytrain_pred=lm.predict(xtrain)
ytest_pred=lm.predict(xtest)

"""Predicts house prices.

Two Predictions
Training prediction
Testing prediction"""


df=pd.DataFrame(ytrain_pred,ytrain)
df=pd.DataFrame(ytest_pred,ytest)

#Predicts house prices.

Two Predictions
Training prediction
Testing prediction

from sklearn.metrics import mean_squared_error, r2_score

"""Uses
mean_squared_error

Calculates prediction error.

r2_score

Calculates accuracy."""

mse=mean_squared_error(ytest,ytest_pred)
print(mse)

"""Finds average squared error.

Theory

Formula:
MSE=
n
1
	​

∑(y−
y
^
	​

)
2

Lower MSE = better model"""

mse=mean_squared_error(ytrain_pred,ytrain)
print(mse)

#Checks training performance.

plt.scatter(ytrain ,ytrain_pred,c='blue',marker='o',label='Training data')
plt.scatter(ytest,ytest_pred ,c='lightgreen',marker='s',label='Test data')

"""Plots:

training predictions
testing predictions"""

plt.xlabel('True values')
plt.ylabel('Predicted')
#Adds graph labels.
plt.title("True value vs Predicted value"
#Adds graph title.
plt.legend(loc= 'upper left')
#Shows labels for graph symbols.
#plt.hlines(y=0,xmin=0,xmax=50)
plt.plot()
plt.show()


"""Final Theory Summary
Concept	Meaning
Linear Regression	Predict continuous values
Training Data	Data used to learn
Testing Data	Data used to test
MSE	Prediction error
R² Score	Accuracy measurement
Regression Line	Best fit line
Polyfit	Finds regression equation
Predict	Predicts output
Scatter Plot	Shows data points
Viva Questions
1. Why use Linear Regression?

To predict continuous values.

2. What is dependent variable?

Output variable.

3. What is independent variable?

Input variable.

4. What is MSE?

Average squared prediction error.

5. What is R² score?

Measures model accuracy.

6. Why split data?

To test model on unseen data.

7. What is training?

Model learning process.

8. What is testing?

Checking model performance."""


"""
Linear Regression Program – Complete Theory Notes
What is this code about?

This program is based on Linear Regression, one of the most important Machine Learning algorithms.

The code performs:

Predicting values using past data
Finding relationship between input and output
Drawing regression graph
Measuring prediction accuracy

This program has 2 parts:

Simple Linear Regression
Predicting 12th marks using 10th marks
Multiple Linear Regression
Predicting California house prices using multiple house features
1. Linear Regression
Meaning

Linear Regression is a Supervised Machine Learning Algorithm used to predict continuous numerical values.

Example:

Predict house price
Predict marks
Predict salary
Predict temperature
2. Purpose of this Program

This program is used to:

Learn relationship between variables
Predict future values
Analyze data patterns
Measure prediction accuracy
Visualize regression line
3. Real Life Examples
Input	Output
Study hours	Exam marks
Experience	Salary
House size	House price
Temperature	Ice cream sales
4. Types Used in This Program
A) Simple Linear Regression

Uses:

One input variable
One output variable

Example:

10th marks → 12th marks

Formula:

Y=mX+b
m
b
-10
-8
-6
-4
-2
2
4
6
8
10
-10
-5
5
10
y-intercept
x-intercept

Where:

Y = predicted output
X = input
m = slope
b = intercept
B) Multiple Linear Regression

Uses:

Multiple input variables
One output variable

Example:

Income
Age
Rooms
Location

→ Predict house price

Formula:

Y=b
0
	​

+b
1
	​

X
1
	​

+b
2
	​

X
2
	​

+⋯+b
n
	​

X
n
	​


5. Theory Concepts Used
A) Supervised Learning

In supervised learning:

Input and output both are given
Machine learns relationship from data

Example:

Input	Output
95	85
85	95
B) Independent Variable

Also called:

Input variable
Feature

Example:

10th marks
House income

Represented as:

X
C) Dependent Variable

Also called:

Output variable
Target variable

Example:

12th marks
House price

Represented as:

Y
D) Regression Line

Best fit straight line passing through data points.

Purpose:

Minimize prediction error
Predict unknown values
E) Least Square Method

Linear Regression uses:

Least Square Method

Purpose:

Reduce error between actual and predicted values

Formula:

∑(y−
y
^
	​

)
2

Where:

y = actual value
ŷ = predicted value
6. Important Functions Used
1. NumPy

Used for:

Arrays
Mathematical calculations

Example:

Store marks data
2. Pandas

Used for:

Table handling
Dataset processing

Example:

DataFrames
3. Matplotlib

Used for:

Graphs
Charts
Visualization
4. np.polyfit()

Purpose:

Creates best fit regression equation

Syntax:

np.polyfit(x, y, 1)

Here:

x = input
y = output
1 = straight line
5. predict()

Purpose:

Predict output values

Example:

Predict marks
Predict house prices
7. Performance Evaluation Concepts
A) Mean Squared Error (MSE)

Measures prediction error.

Formula:

MSE=
n
1
	​

∑(y−
y
^
	​

)
2

Meaning:

Lower MSE = better model
B) R² Score

Measures model accuracy.

Formula:

R
2
=1−
SST
SSR
	​


Range:

0 → poor model
1 → perfect model

Example:

0.48 means model explains 48% variation
8. Why Train-Test Split is Used?

Dataset is divided into:

Training data
Testing data

Purpose:

Prevent overfitting
Check real performance

Common Split:

80% training
20% testing
9. Why We Use This Code?

This code helps to:

Predict future values
Analyze relationships
Build ML models
Evaluate accuracy
Visualize data
Learn regression concepts
10. Advantages of Linear Regression
Advantages
Simple and easy
Fast training
Easy interpretation
Good for numerical prediction
Works well on linear data
11. Disadvantages of Linear Regression
Disadvantages
Works poorly on non-linear data
Sensitive to outliers
Assumes linear relationship
Accuracy may be low on complex data
12. Applications of Linear Regression
Field	Use
Education	Predict marks
Finance	Predict stock prices
Healthcare	Predict patient risk
Real Estate	Predict house prices
Business	Sales forecasting
13. Graph Concept

The graph shows:

Actual points
Predicted points
Best fit line

Purpose:

Understand prediction visually
Compare actual vs predicted values
14. Output Meaning
Simple Regression Output

Equation example:

Y=0.6438X+26.78

Meaning:

If marks increase,
predicted marks also increase
House Price Prediction Output

The model predicts:

California house prices
using multiple features
15. Overall Workflow / Algorithm Steps
Algorithm for Linear Regression Program
Step 1:

Import required libraries

Step 2:

Load dataset

Step 3:

Prepare input and output variables

Step 4:

Split dataset into training and testing

Step 5:

Create Linear Regression model

Step 6:

Train the model using training data

Step 7:

Predict output values

Step 8:

Calculate accuracy using:

MSE
R² Score
Step 9:

Plot graph for visualization

Step 10:

Analyze prediction performance

16. Final Conclusion

This program demonstrates:

Simple Linear Regression
Multiple Linear Regression
Prediction techniques
Error calculation
Accuracy measurement
Data visualization

It is one of the most basic and important Machine Learning programs used for predicting continuous numerical values.
"""