    # -*- coding: utf-8 -*-
"""Assignment7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tRtfJnVwACsbiWA7MiCkNr65AA4_sdpj



    This code is about Text Processing and Sentiment Analysis using NLTK and Machine Learning.

It performs:

Sentence Tokenization
Word Tokenization
Frequency Distribution
Stopword Removal
Stemming
Lemmatization
POS Tagging
Sentiment Analysis using Naive Bayes
"""

pip install nltk

pip install --upgrade pip

"""Install Libraries
pip install nltk
pip install --upgrade pip
Explanation
nltk = Natural Language Toolkit
It is used for NLP tasks like tokenization, stemming, tagging etc.
Use

Used in:

Chatbots
Text analysis
Google Translate
Sentiment analysis"""

import nltk
from nltk.tokenize import sent_tokenize
nltk.download('punkt')

"""Explanation
punkt is a pretrained tokenizer model.
sent_tokenize() breaks paragraph into sentences."""

#This is the sample paragraph.
text="""Hello Mr. Smith, how are you doing today ? The weather is great, and the city is awesome ! The sky is pinkish-blue. You shouldn't eat cardboard """
tokenized_text=sent_tokenize(text)
print(tokenized_text)

"""Logic

The paragraph is split wherever sentence ends (. ? !).

Real Life Use
News article splitting
Voice assistants
Chatbot understanding"""

from nltk.tokenize import word_tokenize
tokenized_word=word_tokenize(text)
print(tokenized_word)

"""word_tokenize() splits sentence into words.
Output Example
['Hello', 'Mr.', 'Smith', ',', 'how', 'are', 'you', ...]
Logic

Every word and punctuation becomes separate token.

Use

Used before:

Text classification
Spam detection
Sentiment analysis"""

from nltk.probability import FreqDist
fdist = FreqDist(tokenized_word)
print(fdist)

"""Explanation

Counts how many times each word appears.

Example
the -> 2 times
is -> 2 times
Logic

Creates dictionary-like structure:

key = word
value = frequency
Use
Keyword extraction
Word popularity
Trend analysis"""


from nltk.corpus import stopwords
nltk.download('stopwords')
stop_words=set(stopwords.words("english"))
print(stop_words)

"""What are Stopwords?

Common words with little meaning:

is
are
the
a
an"""

filtered_sent=[]
for w in tokenized_word:
    if w not in stop_words:
        filtered_sent.append(w)
print("Tokenized Sentence:",tokenized_word)
print("Filterd Sentence:",filtered_sent)

"""Example

Before:

['The', 'weather', 'is', 'great']

After:

['weather', 'great']
Logic

Important words are kept.
Unnecessary words removed.

Use

Improves:

Search engines
ML model accuracy
Faster processing"""


from nltk.stem import PorterStemmer
from nltk.tokenize import sent_tokenize, word_tokenize

ps = PorterStemmer()

stemmed_words=[]
for w in filtered_sent:
    stemmed_words.append(ps.stem(w))

print("Filtered Sentence:",filtered_sent)
print("Stemmed Sentence:",stemmed_words)

"""Explanation

Stemming reduces word to root form.

Examples
Original	Stem
playing	play
studies	studi
flying	fli
Logic

Removes suffixes:

ing
ed
ly
Use

Used in:

Search engines
Text mining
Information retrieval"""

from nltk.stem.wordnet import WordNetLemmatizer
import nltk
nltk.download('wordnet')
lem = WordNetLemmatizer()

"""Example
word = "flying"

print("Lemmatized Word:",lem.lemmatize(word,"v"))
Output
fly
Difference Between Stemming and Lemmatization
Stemming	Lemmatization
Cuts word roughly	Uses dictionary
Faster	More accurate
Example: studi	Example: study"""

from nltk.stem.porter import PorterStemmer
stem = PorterStemmer()

word = "flying"
print("Lemmatized Word:",lem.lemmatize(word,"v"))
print("Stemmed Word:",stem.stem(word))

sent = "Albert Einstein was born in Ulm, Germany in 1879."

tokens=nltk.word_tokenize(sent)
print(tokens)

import nltk
nltk.download('averaged_perceptron_tagger')
nltk.pos_tag(tokens)

"""Explanation

Identifies grammar role of each word.

Example
Word	Tag	Meaning
Albert	NNP	Proper noun
was	VBD	Verb
born	VBN	Verb
Germany	NNP	Proper noun
Use
Grammar checking
Speech recognition
Chatbots
Machine translation"""

import nltk
import pandas as pd
data=pd.read_csv('/home/gescoe/Desktop/TEB30/train.tsv' , sep='\t')

"""Reads TSV dataset.

TSV = Tab Separated Values
Dataset contains:
Phrase
Sentiment"""
data.head()

data.info()
"""Shows:

rows
columns
datatype
null values"""

data.Sentiment.value_counts()

"""Explanation

Counts reviews in each sentiment class.

Example:

Sentiment	Meaning
0	Negative
1	Somewhat Negative
2	Neutral
3	Somewhat Positive
4	Positive"""

import matplotlib.pyplot as plt
Sentiment_count=data.groupby('Sentiment').count()
plt.bar(Sentiment_count.index.values, Sentiment_count['Phrase'])
plt.xlabel('Review Sentiments')
plt.ylabel('Number of Review')
plt.show()
"""Explanation

Displays sentiment distribution graph.

Use

Helps visualize:

Positive reviews
Negative reviews
Neutral reviews"""

from sklearn.feature_extraction.text import CountVectorizer
from nltk.tokenize import RegexpTokenizer
token = RegexpTokenizer(r'[a-zA-Z0-9]+')
"""Explanation

Removes punctuation and keeps:

alphabets
numbers

Meaning of Parameters
Parameter	Meaning
lowercase=True	Convert to lowercase
stop_words='english'	Remove stopwords
ngram_range=(1,1)	Single words only
tokenizer	Custom tokenizer"""
cv = CountVectorizer(lowercase=True,stop_words='english',ngram_range = (1,1),tokenizer = token.tokenize)
text_counts= cv.fit_transform(data['Phrase'])
"""ogic

Machine Learning cannot understand text.

So words converted into numeric vectors.

Example:

Word	Count
good	2
bad	1"""
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    text_counts, data['Sentiment'], test_size=0.3, random_state=1)


"""xplanation

Naive Bayes is a probabilistic ML algorithm.

Works very well for:

text classification
spam filtering
sentiment analysis"""
from sklearn.naive_bayes import MultinomialNB
from sklearn import metrics
clf = MultinomialNB().fit(X_train, y_train)
predicted= clf.predict(X_test)
print("MultinomialNB Accuracy:",metrics.accuracy_score(y_test, predicted))
"""Logic

Model learns:

which words indicate positive sentiment
which words indicate negative sentiment

Example:

amazing → positive
worst → negative"""
from sklearn.feature_extraction.text import TfidfVectorizer
tf=TfidfVectorizer()
text_tf= tf.fit_transform(data['Phrase'])

print(text_tf)

"""xplanation

Checks how many predictions are correct.

Formula:

Accuracy=
Total Predictions
Correct Predictions
	​


Example:

90 correct out of 100
Accuracy = 90%


What is TF-IDF?

TF-IDF gives importance score to words.

Logic
Common words get low score
Important rare words get high score

Example:

"movie" appears everywhere → low importance
"fantastic" appears less → high importance
Formula

TF-IDF=TF×IDF

Where:

TF = Term Frequency
IDF = Inverse Document Frequency
Why TF-IDF Better than CountVectorizer?
CountVectorizer	TF-IDF
Counts words only	Gives importance
Simple	More intelligent
Less accurate sometimes	Better accuracy"""

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    text_tf, data['Sentiment'], test_size=0.3, random_state=123)

#Model generation
from sklearn.naive_bayes import MultinomialNB
from sklearn import metrics
clf = MultinomialNB().fit(X_train, y_train)
predicted= clf.predict(X_test)
print("MultinomialNB Accuracy:",metrics.accuracy_score(y_test, predicted))

"""Text
 ↓
Sentence Tokenization
 ↓
Word Tokenization
 ↓
Stopword Removal
 ↓
Stemming/Lemmatization
 ↓
Convert Text → Numbers
 ↓
Train ML Model
 ↓
Predict Sentiment
 ↓
Check Accuracy
Viva / Oral Questions with Answers
What is NLP?

NLP is a field of AI that helps computers understand human language.

What is Tokenization?

Breaking text into sentences or words.

What are Stopwords?

Common words with little meaning like:
is, the, are

Difference Between Stemming and Lemmatization?
Stemming cuts word roughly.
Lemmatization converts to proper dictionary root word.
Why Convert Text into Numbers?

ML algorithms understand only numeric data.

What is CountVectorizer?

Converts text into word-count vectors.

What is TF-IDF?

Technique that gives importance score to words.

What is Naive Bayes?

Probability-based classification algorithm used for text classification.

Why Naive Bayes Works Well for NLP?

Because text data contains word frequencies and probabilities.ss"""



"""
Text Processing and Sentiment Analysis using NLTK and Machine Learning
What is this Code About?

This program is based on Natural Language Processing (NLP) and Machine Learning.

The code performs different text processing operations using the Python library NLTK and then applies Sentiment Analysis using the Naive Bayes Algorithm.

The program processes text step-by-step like a human language understanding system.

It performs:

Sentence Tokenization
Word Tokenization
Frequency Distribution
Stopword Removal
Stemming
Lemmatization
POS Tagging
Text Vectorization
Sentiment Classification using Naive Bayes

The final goal is to predict whether text/reviews are:

Positive
Negative
Neutral
Theory Concepts
1. Natural Language Processing (NLP)
Meaning

NLP is a branch of Artificial Intelligence that helps computers understand human language.

Uses
Chatbots
Google Translate
Voice Assistants
Spam Detection
Sentiment Analysis
Example

Input:

“Movie was fantastic”

Computer understands:

movie → subject
fantastic → positive emotion
2. Tokenization

Tokenization means breaking text into smaller parts.

There are two types:

A) Sentence Tokenization

Paragraph → Sentences

Example

Input:

Hello. How are you?

Output:

Hello.
How are you?
Purpose

Helps computer understand sentence boundaries.

Uses
Chatbots
News article analysis
Voice assistants
B) Word Tokenization

Sentence → Words

Example

Input:

Weather is great

Output:

Weather
is
great
Purpose

Separates words for analysis.

Uses
Spam filtering
Text classification
Search engines
3. Frequency Distribution
Meaning

Counts how many times each word appears.

Example
Word	Count
the	5
good	2
Purpose

Finds important or repeated words.

Uses
Trend analysis
Keyword extraction
Text mining
4. Stopword Removal
What are Stopwords?

Common words with very little meaning.

Examples:

is
are
the
an
Example

Before:

The weather is great

After:

weather great

Purpose

Removes unnecessary words.

Advantages
Faster processing
Better ML accuracy
Reduces noise
Disadvantages
Sometimes removes meaningful words
5. Stemming
Meaning

Reduces words to root form.

Example
Original Word	Stemmed Word
playing	play
studies	studi
flying	fli
Logic

Removes suffixes like:

ing
ed
ly
Uses
Search engines
Information retrieval
NLP systems
Advantages
Fast
Simple
Disadvantages
Words may become incorrect

Example:

study → studi

6. Lemmatization
Meaning

Converts words into proper dictionary root words.

Example
Original	Lemmatized
flying	fly
studies	study
Difference Between Stemming and Lemmatization
Stemming	Lemmatization
Rough cutting	Dictionary-based
Faster	More accurate
Advantages
Gives meaningful words
More accurate
Disadvantages
Slower than stemming
7. POS Tagging (Part of Speech Tagging)
Meaning

Identifies grammatical role of each word.

Example
Word	Tag	Meaning
Albert	NNP	Proper Noun
was	VBD	Verb
Germany	NNP	Proper Noun
Uses
Grammar checking
Machine translation
Speech recognition
8. CountVectorizer
Meaning

Machine Learning algorithms understand only numbers.

CountVectorizer converts text into numeric vectors.

Example

Sentence:

movie is good

Vector:

movie = 1
good = 1
Purpose

Converts words into machine-readable format.

Advantages
Simple
Fast
Disadvantages
Treats all words equally
Does not understand importance
9. TF-IDF (Term Frequency – Inverse Document Frequency)
Meaning

Gives importance score to words.

Formula

TF-IDF=TF×IDF

Where:

TF = Term Frequency
IDF = Inverse Document Frequency
Logic
Common words → low importance
Rare important words → high importance
Example
Word	Importance
movie	Low
fantastic	High
Advantages
Better accuracy
Intelligent weighting
Disadvantages
More computation required
10. Naive Bayes Algorithm
Meaning

Naive Bayes is a probability-based Machine Learning classification algorithm.

Used mainly for:

Sentiment Analysis
Spam Detection
Text Classification
Formula
P(A∣B)=
P(B)
P(B∣A)P(A)
	​

P(A)
P(B∣A)
P(B∣¬A)
P(A∣B)=
P(B)
P(B∣A)P(A)
	​

≈0.68,P(B)≈0.25
P(B)=0.25
P(B|A)P(A)=0.17
P(A|B)~0.68
Posterior = useful evidence / total evidence

Where:

P(A∣B) = Probability of A given B
P(B∣A) = Probability of B given A
Logic

Model learns:

amazing → positive
worst → negative
Advantages
Fast
Works very well for text data
Easy to implement
Disadvantages
Assumes features are independent
Sometimes less accurate on complex data
Sentiment Analysis
Meaning

Detects emotion/opinion from text.

Sentiment Classes
Value	Meaning
0	Negative
1	Somewhat Negative
2	Neutral
3	Somewhat Positive
4	Positive
Example

Review:

“Movie was amazing”

Prediction:

Positive

Purpose of This Program

The purpose of this code is to:

Understand text data
Clean and preprocess text
Convert text into numbers
Train Machine Learning model
Predict sentiment of reviews
Measure prediction accuracy
Real Life Applications
Chatbots
Review analysis
Social media monitoring
Spam filtering
Customer feedback systems
Recommendation systems
Advantages of This Complete System
Automates text analysis
Fast prediction
Good accuracy
Handles large text data
Useful in real-world NLP applications
Disadvantages
Needs large dataset for better accuracy
Naive Bayes assumptions may reduce accuracy
Context understanding is limited
Sarcasm/emotions are difficult to detect
Why Do We Perform This Program?

We perform this program to:

Teach computer how to understand language
Analyze opinions automatically
Classify reviews into sentiments
Build intelligent NLP systems
Improve decision-making using text data
Overall Workflow / Algorithm
Step-by-Step Procedure
Step 1

Import required libraries like:

NLTK
Pandas
Scikit-learn
Step 2

Download NLP resources:

punkt
stopwords
wordnet
Step 3

Take input text or dataset.

Step 4

Perform Sentence Tokenization.

Step 5

Perform Word Tokenization.

Step 6

Find Frequency Distribution of words.

Step 7

Remove Stopwords.

Step 8

Apply:

Stemming
Lemmatization
Step 9

Perform POS Tagging.

Step 10

Load sentiment dataset.

Step 11

Visualize sentiment distribution using graph.

Step 12

Convert text into numeric vectors using:

CountVectorizer
TF-IDF
Step 13

Split dataset into:

Training data
Testing data
Step 14

Train Naive Bayes model.

Step 15

Predict sentiment for test data.

Step 16

Calculate model accuracy.

Step 17

Display final results.

Final Conclusion

This program demonstrates a complete NLP pipeline for text processing and sentiment analysis.

The system:

Cleans text
Converts text into meaningful features
Uses Machine Learning for classification
Predicts sentiment effectively

It is one of the most fundamental and important NLP projects used in real-world AI applications.
"""