# -*- coding: utf-8 -*-
"""Assignment4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-ETIAP1-Au-qCs9WemOJXx4Smn4qqO1j
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

"""Explanation
1. pandas (pd)

Used for:

handling tables/data
creating DataFrames

Example:
Like Excel sheet handling in Python.

2. numpy (np)

Used for:

arrays
mathematical operations

Example:
Store marks or numbers efficiently.

3. matplotlib.pyplot (plt)

Used for:

graphs
charts
visualization

Example:
Show regression line and points."""

x=np.array([95,85,80,70,60])
y=np.array([85,95,70,65,70])

"""Explanation

Here:

x = marks of students in 10th
y = marks of students in 12th

This is supervised learning data.

x → Independent variable
y → Dependent variable

We want to predict:

If 10th marks are known, what will be 12th marks?"""

model=np.polyfit(x,y,1)

"""Create Linear Regression Model
Explanation

np.polyfit() creates the best fit line.

Syntax
np.polyfit(x,y,degree)
Parameters
x → input values
y → output values
1 → degree 1 means straight line

Theory Behind It

This function uses:

Least Square Method

It tries to minimize prediction error.

Formula:

Y=mX+b
Where:

m = slope
b = intercept

Output of model
array([0.64383562, 26.78082192])

Meaning:

slope = 0.6438
intercept = 26.78

Equation becomes:

Y=0.6438X+26.78"""

predict=np.poly1d(model)

"""Explanation

Creates a prediction equation from model.

Now Python can calculate Y for any X."""
predict(65)

"""Explanation

Predicts 12th marks when 10th marks = 65.

Internally

Y=0.6438(65)+26.78

Result ≈ 68.6

Real Life Logic

Student got:

65 marks in 10th

Model predicts:

around 68 marks in 12th"""

y_pred=predict(x)
y_pred

"""Explanation

Predicts Y values for all X values.

Example
Actual Y	Predicted Y
85	81.5
95	87.9
Use

Used for:

checking model performance
comparing actual vs predicted"""
from sklearn.metrics import r2_score
r2_score(y,y_pred)

"""Explanation

Measures accuracy of regression model.

Theory
R² Score

Formula:
R
2
=
SST
SSR
	​


Range:

0 → bad model
1 → perfect model
Your Output
0.48

Meaning:

model explains 48% variation
average model"""

y_line = model[1] + model[0]* x

"""Creates equation line points.

Logic
y = mx + b

Where:

model[0] = slope
model[1] = intercept"""
plt.plot(x, y_line, c = 'r')
plt.scatter(x, y_pred)
plt.scatter(x,y,c='r')

"""Explanation
1. plt.plot()

Draws regression line.

2. plt.scatter(x,y_pred)

Shows predicted points.

3. plt.scatter(x,y,c='r')

Shows actual points.

Graph Logic

Graph helps visualize:

actual data
predicted data
best fit line"""



import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.datasets import fetch_california_housing
housing=fetch_california_housing()
data=pd.DataFrame(housing.data)
"""Explanation

Loads California house dataset.

Dataset contains:

house information
house prices
Converts dataset into table form."""

data.columns=housing.feature_names
data.head()
"""Adds meaningful column names.

Examples:

MedInc → median income
HouseAge → house age

data.head() shows first 5 rows."""

data['PRICE']=housing.target

"""Explanation

Adds house prices column.

Target variable:

PRICE"""

data.isnull().sum()

"""Explanation

Checks empty values in dataset.

Why Important?

Missing values can affect prediction accuracy."""

x=data.drop(['PRICE'],axis=1)
y=data['PRICE']

"""x

Contains input features.

y

Contains target/output.

Example

Inputs:

income
rooms
age

Output:

house price"""
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,random_state=0)


"""Splits data into:

training data
testing data
Meaning
80% Data

Used for training.

20% Data

Used for testing.

Theory
Why Split Data?

If we test on same training data:

model may memorize data
wrong accuracy comes

Testing on new data checks real performance."""

import sklearn
from sklearn.linear_model import LinearRegression
lm=LinearRegression()
#Creates Linear Regression object.

model=lm.fit(xtrain,ytrain)
"""Model learns patterns from training data.

Theory

Training means:

machine studies data
finds relationships
creates prediction equation"""

ytrain_pred=lm.predict(xtrain)
ytest_pred=lm.predict(xtest)

"""Predicts house prices.

Two Predictions
Training prediction
Testing prediction"""


df=pd.DataFrame(ytrain_pred,ytrain)
df=pd.DataFrame(ytest_pred,ytest)

#Predicts house prices.

Two Predictions
Training prediction
Testing prediction

from sklearn.metrics import mean_squared_error, r2_score

"""Uses
mean_squared_error

Calculates prediction error.

r2_score

Calculates accuracy."""

mse=mean_squared_error(ytest,ytest_pred)
print(mse)

"""Finds average squared error.

Theory

Formula:
MSE=
n
1
	​

∑(y−
y
^
	​

)
2

Lower MSE = better model"""

mse=mean_squared_error(ytrain_pred,ytrain)
print(mse)

#Checks training performance.

plt.scatter(ytrain ,ytrain_pred,c='blue',marker='o',label='Training data')
plt.scatter(ytest,ytest_pred ,c='lightgreen',marker='s',label='Test data')

"""Plots:

training predictions
testing predictions"""

plt.xlabel('True values')
plt.ylabel('Predicted')
#Adds graph labels.
plt.title("True value vs Predicted value"
#Adds graph title.
plt.legend(loc= 'upper left')
#Shows labels for graph symbols.
#plt.hlines(y=0,xmin=0,xmax=50)
plt.plot()
plt.show()


"""Final Theory Summary
Concept	Meaning
Linear Regression	Predict continuous values
Training Data	Data used to learn
Testing Data	Data used to test
MSE	Prediction error
R² Score	Accuracy measurement
Regression Line	Best fit line
Polyfit	Finds regression equation
Predict	Predicts output
Scatter Plot	Shows data points
Viva Questions
1. Why use Linear Regression?

To predict continuous values.

2. What is dependent variable?

Output variable.

3. What is independent variable?

Input variable.

4. What is MSE?

Average squared prediction error.

5. What is R² score?

Measures model accuracy.

6. Why split data?

To test model on unseen data.

7. What is training?

Model learning process.

8. What is testing?

Checking model performance."""