    # -*- coding: utf-8 -*-
"""Assignment7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tRtfJnVwACsbiWA7MiCkNr65AA4_sdpj



    This code is about Text Processing and Sentiment Analysis using NLTK and Machine Learning.

It performs:

Sentence Tokenization
Word Tokenization
Frequency Distribution
Stopword Removal
Stemming
Lemmatization
POS Tagging
Sentiment Analysis using Naive Bayes
"""

pip install nltk

pip install --upgrade pip

"""Install Libraries
pip install nltk
pip install --upgrade pip
Explanation
nltk = Natural Language Toolkit
It is used for NLP tasks like tokenization, stemming, tagging etc.
Use

Used in:

Chatbots
Text analysis
Google Translate
Sentiment analysis"""

import nltk
from nltk.tokenize import sent_tokenize
nltk.download('punkt')

"""Explanation
punkt is a pretrained tokenizer model.
sent_tokenize() breaks paragraph into sentences."""

#This is the sample paragraph.
text="""Hello Mr. Smith, how are you doing today ? The weather is great, and the city is awesome ! The sky is pinkish-blue. You shouldn't eat cardboard """
tokenized_text=sent_tokenize(text)
print(tokenized_text)

"""Logic

The paragraph is split wherever sentence ends (. ? !).

Real Life Use
News article splitting
Voice assistants
Chatbot understanding"""

from nltk.tokenize import word_tokenize
tokenized_word=word_tokenize(text)
print(tokenized_word)

"""word_tokenize() splits sentence into words.
Output Example
['Hello', 'Mr.', 'Smith', ',', 'how', 'are', 'you', ...]
Logic

Every word and punctuation becomes separate token.

Use

Used before:

Text classification
Spam detection
Sentiment analysis"""

from nltk.probability import FreqDist
fdist = FreqDist(tokenized_word)
print(fdist)

"""Explanation

Counts how many times each word appears.

Example
the -> 2 times
is -> 2 times
Logic

Creates dictionary-like structure:

key = word
value = frequency
Use
Keyword extraction
Word popularity
Trend analysis"""


from nltk.corpus import stopwords
nltk.download('stopwords')
stop_words=set(stopwords.words("english"))
print(stop_words)

"""What are Stopwords?

Common words with little meaning:

is
are
the
a
an"""

filtered_sent=[]
for w in tokenized_word:
    if w not in stop_words:
        filtered_sent.append(w)
print("Tokenized Sentence:",tokenized_word)
print("Filterd Sentence:",filtered_sent)

"""Example

Before:

['The', 'weather', 'is', 'great']

After:

['weather', 'great']
Logic

Important words are kept.
Unnecessary words removed.

Use

Improves:

Search engines
ML model accuracy
Faster processing"""


from nltk.stem import PorterStemmer
from nltk.tokenize import sent_tokenize, word_tokenize

ps = PorterStemmer()

stemmed_words=[]
for w in filtered_sent:
    stemmed_words.append(ps.stem(w))

print("Filtered Sentence:",filtered_sent)
print("Stemmed Sentence:",stemmed_words)

"""Explanation

Stemming reduces word to root form.

Examples
Original	Stem
playing	play
studies	studi
flying	fli
Logic

Removes suffixes:

ing
ed
ly
Use

Used in:

Search engines
Text mining
Information retrieval"""

from nltk.stem.wordnet import WordNetLemmatizer
import nltk
nltk.download('wordnet')
lem = WordNetLemmatizer()

"""Example
word = "flying"

print("Lemmatized Word:",lem.lemmatize(word,"v"))
Output
fly
Difference Between Stemming and Lemmatization
Stemming	Lemmatization
Cuts word roughly	Uses dictionary
Faster	More accurate
Example: studi	Example: study"""

from nltk.stem.porter import PorterStemmer
stem = PorterStemmer()

word = "flying"
print("Lemmatized Word:",lem.lemmatize(word,"v"))
print("Stemmed Word:",stem.stem(word))

sent = "Albert Einstein was born in Ulm, Germany in 1879."

tokens=nltk.word_tokenize(sent)
print(tokens)

import nltk
nltk.download('averaged_perceptron_tagger')
nltk.pos_tag(tokens)

"""Explanation

Identifies grammar role of each word.

Example
Word	Tag	Meaning
Albert	NNP	Proper noun
was	VBD	Verb
born	VBN	Verb
Germany	NNP	Proper noun
Use
Grammar checking
Speech recognition
Chatbots
Machine translation"""

import nltk
import pandas as pd
data=pd.read_csv('/home/gescoe/Desktop/TEB30/train.tsv' , sep='\t')

"""Reads TSV dataset.

TSV = Tab Separated Values
Dataset contains:
Phrase
Sentiment"""
data.head()

data.info()
"""Shows:

rows
columns
datatype
null values"""

data.Sentiment.value_counts()

"""Explanation

Counts reviews in each sentiment class.

Example:

Sentiment	Meaning
0	Negative
1	Somewhat Negative
2	Neutral
3	Somewhat Positive
4	Positive"""

import matplotlib.pyplot as plt
Sentiment_count=data.groupby('Sentiment').count()
plt.bar(Sentiment_count.index.values, Sentiment_count['Phrase'])
plt.xlabel('Review Sentiments')
plt.ylabel('Number of Review')
plt.show()
"""Explanation

Displays sentiment distribution graph.

Use

Helps visualize:

Positive reviews
Negative reviews
Neutral reviews"""

from sklearn.feature_extraction.text import CountVectorizer
from nltk.tokenize import RegexpTokenizer
token = RegexpTokenizer(r'[a-zA-Z0-9]+')
"""Explanation

Removes punctuation and keeps:

alphabets
numbers

Meaning of Parameters
Parameter	Meaning
lowercase=True	Convert to lowercase
stop_words='english'	Remove stopwords
ngram_range=(1,1)	Single words only
tokenizer	Custom tokenizer"""
cv = CountVectorizer(lowercase=True,stop_words='english',ngram_range = (1,1),tokenizer = token.tokenize)
text_counts= cv.fit_transform(data['Phrase'])
"""ogic

Machine Learning cannot understand text.

So words converted into numeric vectors.

Example:

Word	Count
good	2
bad	1"""
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    text_counts, data['Sentiment'], test_size=0.3, random_state=1)


"""xplanation

Naive Bayes is a probabilistic ML algorithm.

Works very well for:

text classification
spam filtering
sentiment analysis"""
from sklearn.naive_bayes import MultinomialNB
from sklearn import metrics
clf = MultinomialNB().fit(X_train, y_train)
predicted= clf.predict(X_test)
print("MultinomialNB Accuracy:",metrics.accuracy_score(y_test, predicted))
"""Logic

Model learns:

which words indicate positive sentiment
which words indicate negative sentiment

Example:

amazing → positive
worst → negative"""
from sklearn.feature_extraction.text import TfidfVectorizer
tf=TfidfVectorizer()
text_tf= tf.fit_transform(data['Phrase'])

print(text_tf)

"""xplanation

Checks how many predictions are correct.

Formula:

Accuracy=
Total Predictions
Correct Predictions
	​


Example:

90 correct out of 100
Accuracy = 90%


What is TF-IDF?

TF-IDF gives importance score to words.

Logic
Common words get low score
Important rare words get high score

Example:

"movie" appears everywhere → low importance
"fantastic" appears less → high importance
Formula

TF-IDF=TF×IDF

Where:

TF = Term Frequency
IDF = Inverse Document Frequency
Why TF-IDF Better than CountVectorizer?
CountVectorizer	TF-IDF
Counts words only	Gives importance
Simple	More intelligent
Less accurate sometimes	Better accuracy"""

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    text_tf, data['Sentiment'], test_size=0.3, random_state=123)

#Model generation
from sklearn.naive_bayes import MultinomialNB
from sklearn import metrics
clf = MultinomialNB().fit(X_train, y_train)
predicted= clf.predict(X_test)
print("MultinomialNB Accuracy:",metrics.accuracy_score(y_test, predicted))

"""Text
 ↓
Sentence Tokenization
 ↓
Word Tokenization
 ↓
Stopword Removal
 ↓
Stemming/Lemmatization
 ↓
Convert Text → Numbers
 ↓
Train ML Model
 ↓
Predict Sentiment
 ↓
Check Accuracy
Viva / Oral Questions with Answers
What is NLP?

NLP is a field of AI that helps computers understand human language.

What is Tokenization?

Breaking text into sentences or words.

What are Stopwords?

Common words with little meaning like:
is, the, are

Difference Between Stemming and Lemmatization?
Stemming cuts word roughly.
Lemmatization converts to proper dictionary root word.
Why Convert Text into Numbers?

ML algorithms understand only numeric data.

What is CountVectorizer?

Converts text into word-count vectors.

What is TF-IDF?

Technique that gives importance score to words.

What is Naive Bayes?

Probability-based classification algorithm used for text classification.

Why Naive Bayes Works Well for NLP?

Because text data contains word frequencies and probabilities.ss"""