# -*- coding: utf-8 -*-
"""Data_Visualization_I(Assignment_No_8).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cAZp4YAcgiDrnc4fKj43GNZ4rZk5WkZa
"""

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

dataset=pd.read_csv('/content/train.csv')
dataset

dataset.info()

dataset.describe()

dataset.dtypes

dataset.isnull().sum()

dataset=pd.read_csv('/content/train.csv')
dataset.info()
dataset

sns.distplot(dataset['Fare'])

"""The Dist Plot
The distplot() shows the histogram distribution of data for a single column. The column name is passed as a parameter to the distplot() function. Let's see how the price of the ticket for each passenger is distributed.
"""

sns.distplot(dataset['Fare'], kde=False)

"""kde(Guassian kernal Density Estimate):
Now you can see there is no line for the kernel density estimation on the plot.

You can also pass the value for the bins parameter in order to see more or less details in the graph. Take a look at he following script:
"""

sns.distplot(dataset['Fare'], kde=False, bins=10)

"""Bins (Height of the bar plot which means how many datapoint are threr in that particular bin)"""

sns.jointplot(x='Age', y='Fare', data=dataset)

"""The Joint Plot
The jointplot()is used to display the mutual distribution of each column. You need to pass three parameters to jointplot. The first parameter is the column name for which you want to display the distribution of data on x-axis. The second parameter is the column name for which you want to display the distribution of data on y-axis. Finally, the third parameter is the name of the data frame.
"""

sns.pairplot(dataset)

"""The paitplot() is a type of distribution plot that basically plots a joint plot for all the possible combination of numeric and Boolean columns in your dataset. You only need to pass the name of your dataset as the parameter to the pairplot() function as shown below:"""

sns.rugplot(dataset['Fare'])

"""he rugplot() is used to draw small bars along x-axis for each point in the dataset. To plot a rug plot, you need to pass the name of the column. Let's plot a rug plot for fare.From the output, you can see that as was the case with the distplot(), most of the instances for the fares have values between 0 and 100."""

sns.barplot(x='Sex', y='Fare', data=dataset)

"""The barplot() is used to display the mean value for each value in a categorical column, against a numeric column. The first parameter is the categorical column, the second parameter is the numeric column while the third parameter is the dataset. For instance, if you want to know the mean value of the age of the male and female passengers,"""

import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

sns.barplot(x='Sex', y='Age', data=dataset, estimator=np.std)

sns.countplot(x='Fare', data=dataset)

sns.boxplot(x='Sex', y='Age', data=dataset)

sns.boxplot(x='Survived', y='Fare', data=dataset)

sns.boxplot(x='Sex', y='Age', data=dataset, hue="Survived")

"""Now in addition to the information about the age of each gender, you can also see the distribution of the passengers who survived. For instance, you can see that among the male passengers, on average more younger people survived as compared to the older ones. Similarly, you can see that the variation among the age of female passengers who did not survive is much greater than the age of the surviving female passengers."""

sns.violinplot(x='Sex', y='Age', data=dataset, hue='Survived')

""" The violinplot() function is used to plot the violin plot. Like the box plot, the first parameter is the categorical column, the second parameter is the numeric column while the third parameter is the dataset. if you look at the bottom of the violin plot for the males who survived (left-orange), you can see that it is thicker than the bottom of the violin plot for the males who didn't survive (left-blue). This means that the number of young male passengers who survived is greater than the number of young male passengers who did not survive. The violin plots convey a lot of information, however, on the downside, it takes a bit of time and effort to understand the violin plots."""

sns.stripplot(x='Sex', y='Age', data=dataset)

"""The stripplot() function is used to plot the violin plot. Like the box plot, the first parameter is the categorical column, the second parameter is the numeric column while the third parameter is the dataset."""

sns.histplot(data=dataset,x='Fare',y='Survived')

"""
Data Visualization using Seaborn & Matplotlib (Titanic Dataset)
What is this code about?

This program performs Data Visualization and Exploratory Data Analysis (EDA) on the Titanic dataset using Python libraries like:

Pandas
NumPy
Matplotlib
Seaborn

The code helps us:

Understand the dataset
Find patterns and relationships
Analyze passenger details like Age, Fare, Sex, Survival
Visualize data using graphs and plots

This is mainly used in:

Data Science
Machine Learning preprocessing
Statistical analysis
Pattern recognition
Theory Concepts
1. Data Visualization
Meaning

Data Visualization means representing data in graphical form so that patterns and trends can be understood easily.

Why it is used?
Easy understanding of large data
Detect outliers and missing values
Compare categories
Find relationships between variables
Example

Instead of reading thousands of rows, a graph quickly shows:

Who survived more?
Fare distribution
Age patterns
Libraries Used
1. Pandas
Purpose

Used for:

Reading CSV files
Handling tables/dataframes
Data cleaning
Example

Reading Titanic dataset.

Advantages
Fast data handling
Easy analysis
Disadvantages
Large datasets may consume memory
2. NumPy
Purpose

Used for:

Numerical operations
Mathematical calculations
Example

Finding standard deviation using np.std

Advantages
Faster calculations
Disadvantages
Complex for beginners
3. Matplotlib
Purpose

Basic plotting library for graphs.

Example

Creating charts and plots.

Advantages
Highly customizable
Disadvantages
More coding required
4. Seaborn
Purpose

Advanced visualization library built on Matplotlib.

Advantages
Beautiful graphs
Easy syntax
Statistical plots available
Disadvantages
Slightly slower than matplotlib
Concepts Used in This Program
1. Dataset Information
Functions Used
info()
describe()
dtypes
isnull().sum()
Purpose

Used to:

Check dataset structure
Find missing values
View statistical summary
Example

Checking passenger age, fare, null values etc.

2. Dist Plot
Meaning

Shows distribution of a single variable.

Graph Used

Histogram + Density Curve

Formula Concept
KDE (Kernel Density Estimation)

Used to estimate probability density.

Example

Distribution of passenger Fare.

Why used?

To check:

Most common values
Data spread
Skewness
Advantages
Easy distribution understanding
Disadvantages
Hard for huge datasets
3. Joint Plot
Meaning

Shows relationship between two variables.

Example

Relationship between:

Age
Fare
Purpose

To see:

Correlation
Trends
Advantages
Combines scatter plot + histogram
Disadvantages
Difficult for categorical data
4. Pair Plot
Meaning

Shows relationships among all numerical columns.

Example

Comparing:

Age
Fare
Survival
Purpose

Used in Machine Learning preprocessing.

Advantages
Multiple comparisons at once
Disadvantages
Slow for large datasets
5. Rug Plot
Meaning

Displays small lines for each data point.

Purpose

Shows data density.

Example

Passenger fare concentration.

Advantages
Simple visualization
Disadvantages
Overlapping in large datasets
6. Bar Plot
Meaning

Shows average/statistical values for categories.

Example

Average fare for males and females.

Formula Used
Mean Formula

x
ˉ
=
n
∑x
	​


Standard Deviation Formula

σ=
N
∑(x−μ)
2
	​

	​


Purpose

Category comparison.

Advantages
Easy comparison
Disadvantages
Cannot show detailed distribution
7. Count Plot
Meaning

Counts occurrences of categorical values.

Example

How many passengers belong to each Fare category.

Purpose

Frequency analysis.

Advantages
Simple understanding
Disadvantages
Not useful for continuous data
8. Box Plot
Meaning

Shows:

Median
Quartiles
Outliers
Formula Concepts
Median

Middle value of sorted data.

Interquartile Range (IQR)

IQR=Q
3
	​

−Q
1
	​


Example

Age distribution by gender.

Purpose

Detect outliers and spread.

Advantages
Excellent outlier detection
Disadvantages
Less intuitive for beginners
9. Violin Plot
Meaning

Combination of:

Box plot
KDE plot
Purpose

Shows distribution shape.

Example

Survival distribution by gender and age.

Advantages
Rich statistical information
Disadvantages
Slightly difficult to interpret
10. Strip Plot
Meaning

Displays all individual data points.

Purpose

Shows exact data distribution.

Advantages
Easy point visualization
Disadvantages
Overlapping for large datasets
11. Hist Plot
Meaning

Histogram-based visualization.

Purpose

Shows frequency distribution.

Example

Fare vs Survival.

Advantages
Good for distribution analysis
Disadvantages
Bin selection affects output
Purpose of this Entire Program

This program is used for:

Exploratory Data Analysis (EDA)
Understanding Titanic dataset
Detecting trends and relationships
Preparing data for Machine Learning
Statistical visualization
Identifying missing values and outliers
Real-Life Applications
Used in:
Data Science projects
Machine Learning preprocessing
Business analytics
Healthcare analytics
Financial analysis
Customer behavior analysis
Advantages of This Program
Easy data understanding
Better visualization
Detect hidden patterns
Supports ML model preparation
Quick statistical insights
Disadvantages
Large datasets may slow plotting
Some graphs are difficult to interpret
Visualization alone cannot predict results
Algorithm / Steps to Perform This Program
Step 1

Import required libraries:

Pandas
NumPy
Matplotlib
Seaborn
Step 2

Load Titanic dataset using CSV file.

Step 3

Check dataset information:

Structure
Data types
Null values
Statistical summary
Step 4

Perform distribution analysis:

Distplot
Histplot
Rugplot
Step 5

Analyze relationships:

Jointplot
Pairplot
Step 6

Perform categorical analysis:

Barplot
Countplot
Step 7

Perform statistical visualization:

Boxplot
Violinplot
Stripplot
Step 8

Interpret graphs and identify:

Trends
Outliers
Distributions
Survival patterns
Step 9

Use insights for Machine Learning or Data Analysis.

Conclusion

This program demonstrates how visualization techniques help analyze and understand datasets effectively. Using Seaborn and Matplotlib, different graph types are created to study passenger information from the Titanic dataset. It is an important concept in Data Science, Machine Learning, and Statistical Analysis.
"""